### ISSUE TITLE
Promises not working (simply returns command?)

### ISSUE THREAD

**Issue by niftylettuce** [sindresorhus/execa#110]
Perhaps I'm using this wrong or the documentation is confusing, but I cannot get `execa` to work properly so I'm going to use [child-process-promise](https://www.npmjs.com/package/child-process-promise)'s `exec` Promise in the meanwhile.

Here's a snippet of code that does not seem to work.  It only returns the command and not the `stdout` from the command executed.  Am I invoking incorrectly or is my usage wrong?

```js
const execa = require('execa');
execa.stdout('echo', [ 'lastsave', '|', 'redis-cli' ]).then(console.log).catch(console.error);
```

Outputs:

```sh
lastsave | redis-cli
```

Full output with `node -i`:

```sh
> const execa = require('execa');
undefined
> execa.stdout('echo', [ 'lastsave', '|', 'redis-cli' ]).then(console.log).catch(console.error);
Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events: { error: [Function: debugDomainError] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] } }
> lastsave | redis-cli
```

I've also tried it with without an array:

```js
const execa = require('execa');
execa.stdout('echo', [ 'lastsave | redis-cli' ]).then(console.log).catch(console.error);
```

Same output.

When I run it without a second argument:

```sh
> execa.stdout('echo lastsave | redis-cli').then(console.log).catch(console.error);
Promise {
  <pending>,
  domain:
   Domain {
     domain: null,
     _events: { error: [Function: debugDomainError] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] } }
> { Error: spawn echo lastsave | redis-cli ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn echo lastsave | redis-cli',
  path: 'echo lastsave | redis-cli',
  spawnargs: [],
  killed: false,
  stdout: '',
  stderr: '',
  failed: true,
  signal: null,
  cmd: 'echo lastsave | redis-cli',
  timedOut: false }
```

It seemed like a drop in replacement for `exec` but I'm a bit confused as the docs show an example that otherwise looks normal.

**Comment by sindresorhus** [comment]
Per the docs, you have to use `execa.shell` if you want it executed as a shell command.

**Comment by kevva** [comment]
If you want to achieve that without using `execa.shell` you'll have to do this:

```js
const echo = execa('echo', ['lastsave']);
const redisCli = execa('redis-cli');

echo.stdout.pipe(redisCli.stdin);

redisCli.then(res => {
	console.log(res.stdout);
});
```
