### ISSUE TITLE
The command cannot be executed

### ISSUE THREAD

**Issue by yxw007** [sindresorhus/execa#1142]
```text
npm error could not determine executable to run
npm error A complete log of this run can be found in: C:\Users\aa479\AppData\Local\npm-cache\_logs\2024-08-11T02_19_50_337Z-debug-0.log
file:///F:/Project/artipub/node_modules/.pnpm/execa@9.3.0/node_modules/execa/lib/return/final-error.js:6
        return new ErrorClass(message, options);
               ^

ExecaError: Command failed with exit code 1: npx conventional-changelog -i CHANGELOG.md -s --commit-path .
    at getFinalError (file:///F:/Project/artipub/node_modules/.pnpm/execa@9.3.0/node_modules/execa/lib/return/final-error.js:6:9)
    at makeError (file:///F:/Project/artipub/node_modules/.pnpm/execa@9.3.0/node_modules/execa/lib/return/result.js:108:16)
    at getAsyncResult (file:///F:/Project/artipub/node_modules/.pnpm/execa@9.3.0/node_modules/execa/lib/methods/main-async.js:167:4)
    at handlePromise (file:///F:/Project/artipub/node_modules/.pnpm/execa@9.3.0/node_modules/execa/lib/methods/main-async.js:150:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at generateChangelog (F:\Project\artipub\scripts\release.ts:139:3)
    at run (F:\Project\artipub\scripts\release.ts:210:3) {
  shortMessage: 'Command failed with exit code 1: npx conventional-changelog -i CHANGELOG.md -s --commit-path .',
  command: 'npx conventional-changelog -i CHANGELOG.md -s --commit-path .',
  escapedCommand: 'npx conventional-changelog -i CHANGELOG.md -s --commit-path .',
  cwd: 'F:\\Project\\artipub\\packages\\core',
  durationMs: 4652.3501,
  failed: true,
  timedOut: false,
  isCanceled: false,
  isGracefullyCanceled: false,
  isTerminated: false,
  isMaxBuffer: false,
  isForcefullyTerminated: false,
  exitCode: 1,
  stdio: [ undefined, undefined, undefined ],
  ipcOutput: [],
  pipedFrom: []
}

```
debug.log content

```
0 verbose cli C:\Users\aa479\.nvmd\versions\22.3.0\node.exe C:\Users\aa479\.nvmd\versions\22.3.0\node_modules\npm\bin\npm-cli.js
1 info using npm@10.8.1
2 info using node@v22.3.0
3 silly config load:file:C:\Users\aa479\.nvmd\versions\22.3.0\node_modules\npm\npmrc
4 silly config load:file:F:\Project\artipub\packages\core\.npmrc
5 silly config load:file:C:\Users\aa479\.npmrc
6 silly config load:file:C:\Users\aa479\.nvmd\versions\22.3.0\etc\npmrc
7 verbose title npm exec conventional-changelog -i CHANGELOG.md -s --commit-path .
8 verbose argv "exec" "--" "conventional-changelog" "-i" "CHANGELOG.md" "-s" "--commit-path" "."
9 verbose logfile logs-max:10 dir:C:\Users\aa479\AppData\Local\npm-cache\_logs\2024-08-11T02_19_50_337Z-
10 verbose logfile C:\Users\aa479\AppData\Local\npm-cache\_logs\2024-08-11T02_19_50_337Z-debug-0.log
11 silly logfile start cleaning logs, removing 2 files
12 silly logfile done cleaning log files
13 silly packumentCache heap:4345298944 maxSize:1086324736 maxEntrySize:543162368
14 http fetch GET 200 https://registry.npmjs.org/conventional-changelog 1082ms (cache revalidated)
15 verbose stack Error: could not determine executable to run
15 verbose stack     at getBinFromManifest (C:\Users\aa479\.nvmd\versions\22.3.0\node_modules\npm\node_modules\libnpmexec\lib\get-bin-from-manifest.js:17:23)
15 verbose stack     at exec (C:\Users\aa479\.nvmd\versions\22.3.0\node_modules\npm\node_modules\libnpmexec\lib\index.js:198:15)
15 verbose stack     at async Npm.exec (C:\Users\aa479\.nvmd\versions\22.3.0\node_modules\npm\lib\npm.js:207:9)
15 verbose stack     at async module.exports (C:\Users\aa479\.nvmd\versions\22.3.0\node_modules\npm\lib\cli\entry.js:74:5)
16 verbose pkgid conventional-changelog@6.0.0
17 error could not determine executable to run
18 verbose cwd F:\Project\artipub\packages\core
19 verbose os Windows_NT 10.0.19045
20 verbose node v22.3.0
21 verbose npm  v10.8.1
22 verbose exit 1
23 verbose code 1
24 error A complete log of this run can be found in: C:\Users\aa479\AppData\Local\npm-cache\_logs\2024-08-11T02_19_50_337Z-debug-0.log
```

I tried to switch, and multiple versions of node (22.3.0,22.6.0 etc) were still swapped

**Comment by yxw007** [comment]
Found the reason, it's because I didn't have conventional-changelog-cli installed
