### ISSUE TITLE
How to get stream output of stdout

### ISSUE THREAD

**Issue by kopax** [sindresorhus/execa#138]
I am using execa to call a bash script:

```node
const { stdout } = await execa.shel(path.join(__dirname, 'script.sh'));
console.log(stdout);
```

I have tried to re-use the code that use `get-stream` but it is throwing error. What is the real way to call a bash script and get the output as if it was the script itself running?

**Comment by SamVerschueren** [comment]
It's a promise, so you need to use `await` or `.then` like in the examples https://github.com/sindresorhus/execa#usage

**Comment by kopax** [comment]
Yes, but we prefere to use `await/async` this is why we downloaded execa on the first place.

By doing like this, we must wait until the script is finish to see the `stdout` which is not very responsive.

Most of the time, it just exceed the maxBuffer and crash.

**Comment by kopax** [comment]
I am still encountering issue to run `.sh` from `.js`:

maxBuffer error. 

Is there a bulletproof solution to do that? 

I was doing with `execa.shellSync(path.join(__dirname, 'before_script.sh'));` but that does not stream the output apparently. Resulting in ENOBUFS error...

```bash

{ Error: spawnSync /bin/sh ENOBUFS
    at Object.spawnSync (internal/child_process.js:977:20)
    at Object.spawnSync (child_process.js:581:24)
    at module.exports.sync (/root/.npm/_npx/145/lib/node_modules/rollup-umd-scripts/node_modules/execa/index.js:337:30)
    at handleShell (/root/.npm/_npx/145/lib/node_modules/rollup-umd-scripts/node_modules/execa/index.js:119:9)
    at Function.module.exports.shellSync (/root/.npm/_npx/145/lib/node_modules/rollup-umd-scripts/node_modules/execa/index.js:364:43)
    at _callee$ (/root/.npm/_npx/145/lib/node_modules/rollup-umd-scripts/bin/scripts-ci/cmds/test.js:26:26)
    at tryCatch (/root/.npm/_npx/145/lib/node_modules/rollup-umd-scripts/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/root/.npm/_npx/145/lib/node_modules/rollup-umd-scripts/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/root/.npm/_npx/145/lib/node_modules/rollup-umd-scripts/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/root/.npm/_npx/145/lib/node_modules/rollup-umd-scripts/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
  errno: 'ENOBUFS',
  code: 'ENOBUFS',
  syscall: 'spawnSync /bin/sh',
  path: '/bin/sh',
  spawnargs: 
   [ '-c',
     '/root/.npm/_npx/145/lib/node_modules/rollup-umd-scripts/bin/scripts-ci/cmds/test.sh' ],
```

**Comment by vhmth** [comment]
@kopax try setting the `stdio` option to `inherit` and remove any piping you might be doing from the child process to your current process.

**Comment by sindresorhus** [comment]
There is now a `buffer` option you could set to `false`.
