### ISSUE TITLE
Assertion `args[1]->IsString()' failed.

### ISSUE THREAD

**Issue by doug-wade** [sindresorhus/execa#155]
I'm using ava and xo, which in turn use execa, and I'm getting [errors trying to upgrade to node 10.13](https://travis-ci.org/doug-wade/clefs/jobs/372830908).

```
lerna ERR! Error: Command failed: npm run test
lerna ERR! gulp[42786]: ../src/node_contextify.cc:628:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
lerna ERR!  1: 0x10003ae75 node::Abort() [/Users/dwade/.nvm/versions/node/v10.13.0/bin/node]
lerna ERR!  2: 0x100039ed3 node::AddEnvironmentCleanupHook(v8::Isolate*, void (*)(void*), void*) [/Users/dwade/.nvm/versions/node/v10.13.0/bin/node]
lerna ERR!  3: 0x1000649b7 node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [/Users/dwade/.nvm/versions/node/v10.13.0/bin/node]
lerna ERR!  4: 0x10023036f v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/Users/dwade/.nvm/versions/node/v10.13.0/bin/node]
lerna ERR!  5: 0x10022f50b v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/Users/dwade/.nvm/versions/node/v10.13.0/bin/node]
lerna ERR!  6: 0x10022ef27 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/Users/dwade/.nvm/versions/node/v10.13.0/bin/node]
lerna ERR!  7: 0x1dbaf145be3d
lerna ERR!  8: 0x1dbaf140d145
lerna ERR!  9: 0x1dbaf148b87d
lerna ERR! 10: 0x1dbaf14118d5
lerna ERR! 11: 0x1dbaf14118d5
lerna ERR! 12: 0x1dbaf14118d5
lerna ERR!
lerna ERR! > generator-clefs-plugin@0.0.1 test /Users/dwade/foss/clefs/packages/generator-clefs-plugin
lerna ERR! > gulp test
lerna ERR!
lerna ERR!
lerna ERR!     at makeError (/Users/dwade/foss/clefs/node_modules/execa/index.js:174:9)
lerna ERR!     at Promise.all.then.arr (/Users/dwade/foss/clefs/node_modules/execa/index.js:278:16)
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
lerna ERR! lerna Command failed: npm run test
lerna ERR! lerna gulp[42786]: ../src/node_contextify.cc:628:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
lerna ERR! lerna  1: 0x10003ae75 node::Abort() [/Users/dwade/.nvm/versions/node/v10.13.0/bin/node]
lerna ERR! lerna  2: 0x100039ed3 node::AddEnvironmentCleanupHook(v8::Isolate*, void (*)(void*), void*) [/Users/dwade/.nvm/versions/node/v10.13.0/bin/node]
lerna ERR! lerna  3: 0x1000649b7 node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [/Users/dwade/.nvm/versions/node/v10.13.0/bin/node]
lerna ERR! lerna  4: 0x10023036f v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/Users/dwade/.nvm/versions/node/v10.13.0/bin/node]
lerna ERR! lerna  5: 0x10022f50b v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/Users/dwade/.nvm/versions/node/v10.13.0/bin/node]
lerna ERR! lerna  6: 0x10022ef27 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/Users/dwade/.nvm/versions/node/v10.13.0/bin/node]
lerna ERR! lerna  7: 0x1dbaf145be3d
lerna ERR! lerna  8: 0x1dbaf140d145
lerna ERR! lerna  9: 0x1dbaf148b87d
lerna ERR! lerna 10: 0x1dbaf14118d5
lerna ERR! lerna 11: 0x1dbaf14118d5
lerna ERR! lerna 12: 0x1dbaf14118d5
lerna ERR! lerna
lerna ERR! lerna > generator-clefs-plugin@0.0.1 test /Users/dwade/foss/clefs/packages/generator-clefs-plugin
lerna ERR! lerna > gulp test
lerna ERR! lerna
lerna ERR! lerna
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! clefs@ test: `lerna run test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the clefs@ test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dwade/.npm/_logs/2018-11-11T04_01_56_153Z-debug.log
```

**Comment by doug-wade** [comment]
See https://github.com/nodejs/node/issues/20285 and https://github.com/nodejs/node/issues/20325 and https://github.com/gulpjs/gulp/issues/2162
