### ISSUE TITLE
Unable to handle ChildProcess error

### ISSUE THREAD

**Issue by lorensr** [sindresorhus/execa#164]
Is there any way I can catch this error?

```js
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn ps ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! packlist@0.1.0 test:e2e: `start-server-and-test start:qa http-get://0.0.0.0:8080 cy:run`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the packlist@0.1.0 test:e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-12-01T05_09_26_197Z-debug.log
Exited with code 1
```

I'm trying:

```js
const server = execa('npm', ['run', start], { stdio: 'inherit' });
server.on('error', (e) => {
  console.log('server.on error');
});
server.catch((e) => {
  console.log('server.catch');
});
```

But neither message is logged.

**Comment by sindresorhus** [comment]
What Node.js version and Execa version? And you have not defined what the `start` variable is.

With:

```js
const server = execa('non-existant', { stdio: 'inherit' });
server.on('error', (e) => {
  console.log('server.on error');
});
server.catch((e) => {
  console.log('server.catch');
});
```

I'm getting the expected:

```
server.on error
server.catch
```

The best would be if you could submit a [failing test](https://github.com/avajs/ava/blob/master/docs/01-writing-tests.md#failing-tests) to prove it's an issue with `execa` and not a mistake on your part.

**Comment by lorensr** [comment]
I'm no longer getting an error. It was trying to run a bash command that wasn't installed on the system.
