### ISSUE TITLE
How to catch "execa" rejection while using events

### ISSUE THREAD

**Issue by OmgImAlexis** [sindresorhus/execa#165]
Is there a way to catch permission errors, etc. from `execa` while also listening to live events from `stdout` and `stderr`? I need to stream the output of `stdout` and `stderr` over websockets so I don't think I can use `.then` as that resolves once the `child_process` finishes.

### Events with no catch handler, invalid uid
```js
const execa = require('execa');

const stream = execa('id', [], {
    uid: 15000 // invalid uid
});

stream.stdout.on('data', chunk => {
    console.log('streaming: ' + chunk.toString());
});
```
```
/Users/xo/code/unraid/api/x.js:7
stream.stdout.on('data', chunk => {
              ^

TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (/Users/xo/code/unraid/api/x.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
```
------

### Events with no catch handler, valid uid
```js
const execa = require('execa');

const stream = execa('id', [], {
    uid: 501 // valid uid
});

stream.stdout.on('data', chunk => {
    console.log('streaming: ' + chunk.toString());
});
```
```
streaming: uid=501(xo) gid=20(staff) groups=20(staff),701(com.apple.sharepoint.group.1),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),33(_appstore),100(_lpoperator),204(_developer),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh)
```
------

### Events with catch handler, invalid uid
```js
const execa = require('execa');

const stream = execa('id', [], {
    uid: 15000 // invalid uid
}).catch(error => {
    console.error(error);
});

stream.stdout.on('data', chunk => {
    console.log('streaming: ' + chunk.toString());
});
```
```
/Users/xo/code/unraid/api/x.js:9
stream.stdout.on('data', chunk => {
              ^

TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (/Users/xo/code/unraid/api/x.js:9:15)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
```
-----

### Events with catch handler, valid uid
```js
const execa = require('execa');

const stream = execa('id', [], {
    uid: 501 // valid uid
}).catch(error => {
    console.error(error);
});

stream.stdout.on('data', chunk => {
    console.log('streaming: ' + chunk.toString());
});
```
```
/Users/xo/code/unraid/api/x.js:9
stream.stdout.on('data', chunk => {
              ^

TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (/Users/xo/code/unraid/api/x.js:9:15)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
```
-----

### No events with catch handler, invalid uid
```js
const execa = require('execa');

const stream = execa('id', [], {
    uid: 15000 // invalid uid
}).catch(error => {
    console.error(error);
});
```
```
{ Error: spawn EPERM
    at ChildProcess.spawn (internal/child_process.js:330:11)
    at Object.exports.spawn (child_process.js:500:9)
    at module.exports (/Users/xo/code/unraid/api/node_modules/execa/index.js:205:26)
    at Object.<anonymous> (/Users/xo/code/unraid/api/x.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10) errno: 'EPERM', code: 'EPERM', syscall: 'spawn' }
```
-----

### No events with catch handler, valid uid
```js
const execa = require('execa');

const stream = execa('id', [], {
    uid: 501 // valid uid
}).catch(error => {
    console.error(error);
});
```
```
```

**Comment by sindresorhus** [comment]
@ehmicky Any ideas?

**Comment by ehmicky** [comment]
From looking at [Node.js core source](https://github.com/nodejs/node/blob/f4f937b296f62c11dfbd3a8f92abac81049b629e/lib/internal/child_process.js#L380) and libuv source ([Unix](https://github.com/libuv/libuv/blob/a74e54bc8fab57c02eabda907e7b5d10451d0a99/src/unix/process.c#L411), [Windows](https://github.com/libuv/libuv/blob/c5593b51dc98715f7f32a919301b5801ebf1a8ce/src/win/process.c#L937)): if `uid` is invalid, no `childProcess` is created. Instead an `error` is thrown synchronously.

I.e. if you get a permission error, there should be no `stdout` nor `stderr` to listen to (since no `childProcess` got created).

You could fix your issue though by checking if `stream.stdout` exists before listening to it:

```js
const execa = require('execa');

const stream = execa('id', [], {
    uid: 15000 // invalid uid
}).catch(error => {
    console.error(error);
});

if (stream.stdout !== undefined) {
    stream.stdout.on('data', chunk => {
         console.log('streaming: ' + chunk.toString());
    });
}
```

**Comment by OmgImAlexis** [comment]
@ehmicky I'll give that a try when I'm back at work. It does sound like it should be fine for my use though. 🙏

**Comment by ehmicky** [comment]
Thanks @OmgImAlexis. Please let us know, so we can close this issue (if it solves your problem).

**Comment by ehmicky** [comment]
@OmgImAlexis did this solve your problem?

**Comment by ehmicky** [comment]
@sindresorhus I think this should close this issue.
