### ISSUE TITLE
How to run sudo apt update and use interactive terminal?

### ISSUE THREAD

**Issue by kopax** [sindresorhus/execa#374]
Within a script, this is what I am trying to run:

```js
    const cmd = 'sudo apt update -y';
    debug(cmd);
    return await execa(cmd, { shell: true });
```

I am failing with:

```
Error: Command failed with exit code 1 (EPERM): sudo apt update -y
    at makeError (execa/lib/error.js:58:11)
    at handlePromise (execa/index.js:112:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  command: 'sudo apt update -y',
  exitCode: 1,
  exitCodeName: 'EPERM',
  stdout: '',
  stderr: '',
  all: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  signal: undefined
}
```

is there a way to get interactive terminal?

**Comment by kopax** [comment]
No, it did not work, I have tried all possible values, it fail when the command has prompt.

**Comment by ehmicky** [comment]
I tried the following on my machine:

```js
const execa = require('execa')

const update = async function () {
  try {
    await execa('sudo apt update -y', { shell: true, stdio: 'inherit' });
  } catch (error) {
    console.log(error)
  }
}

update()
```

Then ran it:

```
$ node update.js
Hit:1 http://se.archive.ubuntu.com/ubuntu disco InRelease
Ign:2 http://dl.google.com/linux/chrome/deb stable InRelease                                                                                                                     
Hit:3 http://se.archive.ubuntu.com/ubuntu disco-updates InRelease                                                                                                                
Hit:4 http://se.archive.ubuntu.com/ubuntu disco-backports InRelease                                                                                                              
Hit:5 http://dl.google.com/linux/chrome/deb stable Release                                                                                                 
Hit:6 http://ppa.launchpad.net/longsleep/golang-backports/ubuntu disco InRelease                                                                      
Hit:7 http://archive.canonical.com/ubuntu disco InRelease                                                                       
Hit:8 http://security.ubuntu.com/ubuntu disco-security InRelease                                          
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
```

I think the difference might be that I have this in my `/etc/sudoers`:

```
ehmicky ALL=(ALL) NOPASSWD:ALL
```
