### ISSUE TITLE
Child process not cancelled or killed

### ISSUE THREAD

**Issue by gjvengelen** [sindresorhus/execa#460]
Hi,
I'm trying to run a test where I spinup my app perform some actions and than cancel the app so my test will actually finish.
But it does not seem to be able to kill the app, could you provide me with some feedback on my implementation:

```[JavaScript]
describe("productOverview", () => {
  let browser;
  let page;
  let subprocess;
  beforeAll(async () => {
    try {
    subprocess = execa("npm run start").stdout.pipe(process.stdout);
    }
    catch(err){
      throw err
    }
    console.log("starting application...");
    await waitForLocalhost({ port: 3000 });
    console.log("Application started");
  });
  beforeEach(async () => {
    //arrange
    browser = await puppeteer.launch({ headless: false });
    page = await browser.newPage();
    await page.goto("http://localhost:3000/");
  });
  afterEach(async () => {
    await browser.close();
  });
  afterAll(() => {
      console.log("Stopping application...")
      subprocess.kill("SIGTERM")
      console.log("Application stopped")
  });
  ```
The end result of my tests is passed but since the process is not killed I end up with `Jest did not exit one second after the test run has completed.` Running with --detectOpenHandles shows the following:
```
  ●  PROCESSWRAP

       9 |   beforeAll(async () => {
      10 |     try {
    > 11 |     subprocess = execa("npm run start").stdout.pipe(process.stdout);
         |                  ^
      12 |     }
      13 |     catch(err){
      14 |       throw err

      at execa (node_modules/execa/index.js:80:26)
      at Object.<anonymous> (e2etest/productsOverview.e2e.spec.js:11:18)


  ●  PIPEWRAP

       9 |   beforeAll(async () => {
      10 |     try {
    > 11 |     subprocess = execa("npm run start").stdout.pipe(process.stdout);
         |                  ^
      12 |     }
      13 |     catch(err){
      14 |       throw err

          at Array.reduce (<anonymous>)
      at execa (node_modules/execa/index.js:80:26)
      at Object.<anonymous> (e2etest/productsOverview.e2e.spec.js:11:18)
      ```

**Comment by ehmicky** [comment]
Hi @gjvengelen,

The argument to `execa` is a command followed by an array of arguments, unless the `shell: true` option is used. So this should be either `execa('npm', ['run', 'start'])` or `execa('npm run start', { shell: true }`).

**Comment by gjvengelen** [comment]
Hi @ehmicky ,

Thnx for your response but both `execa('npm', ['run', 'start'])` or `execa('npm run start', { shell: true })`, are returning the same result as with my first tries.

```
 ●  PROCESSWRAP

       9 |   beforeAll(async () => {
      10 |     console.log("starting application...");
    > 11 |     subprocess = execa('npm run start', {shell: true})
         |                  ^
      12 |     subprocess.stdout.pipe(process.stdout);
      13 |     subprocess.stdout.pipe(process.stderr);
      14 |     await waitForLocalhost({ port: 3000 });

      at execa (node_modules/execa/index.js:80:26)
      at Object.<anonymous> (e2etest/productsOverview.e2e.spec.js:11:18)


  ●  PIPEWRAP

       9 |   beforeAll(async () => {
      10 |     console.log("starting application...");
    > 11 |     subprocess = execa('npm run start', {shell: true})
         |                  ^
      12 |     subprocess.stdout.pipe(process.stdout);
      13 |     subprocess.stdout.pipe(process.stderr);
      14 |     await waitForLocalhost({ port: 3000 });

          at Array.reduce (<anonymous>)
      at execa (node_modules/execa/index.js:80:26)
      at Object.<anonymous> (e2etest/productsOverview.e2e.spec.js:11:18)
```

Could it have something to do with me trying to start an NPM command like this:
`"start": "concurrently \"npm start --prefix frontend\" \"npm start --prefix backend\"",`?

**Comment by ehmicky** [comment]
Which error message do you get if you replace `execa()` by `child_process.spawn()`?

In other words:

```js
const { spawn } = require("child_process")

...

subprocess = spawn("npm run start", { shell: true }).stdout.pipe(process.stdout);
```

**Comment by gjvengelen** [comment]
Same result:
```
Jest has detected the following 2 open handles potentially keeping Jest from exiting:

  ●  PROCESSWRAP

       9 |   beforeAll(async () => {
      10 |     console.log("starting application...");
    > 11 |     subprocess = spawn("npm run start", { shell: true }).stdout.pipe(process.stdout);
         |                  ^
      12 |
      13 |     await waitForLocalhost({ port: 3000 });

      at Object.<anonymous> (e2etest/productsOverview.e2e.spec.js:11:18)


  ●  PIPEWRAP

       9 |   beforeAll(async () => {
    > 11 |     subprocess = spawn("npm run start", { shell: true }).stdout.pipe(process.stdout);
         |                  ^
      12 |
      13 |     await waitForLocalhost({ port: 3000 });
      14 |     console.log("Application started");

          at Array.reduce (<anonymous>)
      at Object.<anonymous> (e2etest/productsOverview.e2e.spec.js:11:18)
```

**Comment by ehmicky** [comment]
Thanks for the additional information @gjvengelen.

Execa is a thin wrapper around `child_process.spawn()`. If you can reproduce this problem with `child_process.spawn()`, this indicates it is not related to Execa, but to a different factor (Jest, Puppeteer, or the test code), so I will close this issue. 

I would suggest posting this issue on the Jest repository instead, but using code samples with `child_process.spawn()` instead to avoid any confusion.
