### ISSUE TITLE
TypeError: arg.replace is not a function

### ISSUE THREAD

**Issue by Differentunic** [sindresorhus/execa#467]
Error:

TypeError: arg.replace is not a function
       at escapeArg (/var/www/html/node_modules/execa/lib/command.js:18:17)
       at /var/www/html/node_modules/execa/lib/command.js:26:46
       at Array.map (<anonymous>)
       at getEscapedCommand (/var/www/html/node_modules/execa/lib/command.js:26:35)
       at execa (/var/www/html/node_modules/execa/index.js:77:25)
       at /var/www/html/index.js:25:22
       at Layer.handle [as handle_request] (/var/www/html/node_modules/express/lib/router/layer.js:95:5)
       at next (/var/www/html/node_modules/express/lib/router/route.js:137:13)
       at Route.dispatch (/var/www/html/node_modules/express/lib/router/route.js:112:3)
       at Layer.handle [as handle_request] (/var/www/html/node_modules/express/lib/router/layer.js:95:5)

My code:
```js
const subprocess = execa(youtubedl.raw(URL, {
    noWarnings: true,
    noCallHome: true,
    noCheckCertificate: true,
    preferFreeFormats: true,
    youtubeSkipDashManifest: true
  }));
  subprocess.stdout.pipe(process.stdout);

  (async () => {
    const {stdout} = await subprocess;
    console.log('child output:', stdout);
  })();
  ```

**Comment by Differentunic** [comment]
I'm not sure if I am misunderstanding how execa works.

**Comment by ehmicky** [comment]
Hi @Differentunic,

The first argument of `execa()` must be a string (the command/binary) and the second argument must be an optional array of arguments. It appears that `youtubedl.raw()` returns an array, so this does not match how `execa()` is meant to be called.

The error message does not make this clear though, so I opened #468 to clarify this.
