### ISSUE TITLE
execaCommandSync fails to parse command arguments with quotes

### ISSUE THREAD

**Issue by MurzNN** [sindresorhus/execa#486]
If I launch an ssh command `ssh user@example.com 'pwd && ls -l'` manually in console - it works well without errors.

But if I try to do the same, using `execa`'s  function execaCommandSync(), using this code:
```js
import {execaCommandSync} from 'execa';

let cmd = "ssh user@example.com 'pwd && ls -l'"
console.log(cmd);
const result = await execaCommandSync(cmd);
console.log(result);
```
I got an error:
```
file:///home/user/test/node_modules/execa/lib/error.js:59
                error = new Error(message);
                        ^

Error: Command failed with exit code 127: ssh user@example.com 'pwd && ls -l'
bash: pwd && ls -l: command not found
    at makeError (file:///home/user/test/node_modules/execa/lib/error.js:59:11)
    at execaSync (file:///home/user/test/node_modules/execa/index.js:193:17)
    at execaCommandSync (file:///home/user/test/node_modules/execa/index.js:234:9)
    at file:///home/user/test/test.mjs:9:22
    at ModuleJob.run (internal/modules/esm/module_job.js:169:25)
    at async Loader.import (internal/modules/esm/loader.js:177:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5) {
  shortMessage: "Command failed with exit code 127: ssh user@example.com 'pwd && ls -l'",
  command: "ssh user@example.com 'pwd && ls -l'",
  escapedCommand: `ssh "user@example.com" "'pwd" "&&" ls "-l'"`,
  exitCode: 127,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'bash: pwd && ls -l: command not found',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

Output of the same command, launched from command line:
```
$ ssh user@example.com 'pwd && ls -l'
/home/user
total 44
drwxr-x--- 1 user user    0 Mar 19  2019 cgi-bin
drwxr-xr-x 1 user user   32 Dec 15  2020 domains
drwxr-xr-x 1 user user   12 Aug 26 22:04 etc
...
```
Seems the problem is with `execa`'s command line parser, it parses quotes wrong, and splits spaces inside quotes to separate command line arguments.

**Comment by MurzNN** [comment]
Similar code with `child_processes` works well:
```js
import { execSync } from 'child_process';

let cmd = "ssh user@example.com 'pwd && ls -l'"
console.log(cmd);
const result = await execSync(cmd);
console.log(result + "");
```

**Comment by sindresorhus** [comment]
From the docs:

> The shell option must be used if the command uses shell-specific features

The equivalent of `execSync` is using `{shell: true}` with Execa.

**Comment by MurzNN** [comment]
Thanks for explanation, with `{shell: true}` all works well! Didn't catch this difference when switching from `execSync`.
