### ISSUE TITLE
Issue running grep with input globs using script interface

### ISSUE THREAD

**Issue by navin-moorthy** [sindresorhus/execa#555]
Error in terminal: `grep: **/*.*: no such file or directory`

```js
const { stdout } = await $({
	shell: true,
})`grep --exclude script/setup.js --exclude script/setup-test-e2e.js --exclude-dir node_modules -i ${search} *.* **/*.*`;
```

References: https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues/357, https://github.com/JoshuaKGoldberg/template-typescript-node-package/pull/349#discussion_r1156155511

**Comment by ehmicky** [comment]
Hi @navin-moorthy,

Which error do you get when running the following command?

```js
import { execFile } from 'child_process'
import { promisify } from 'util'

const pExecFile = promisify(execFile)

const { stdout } = await pExecFile(`grep --exclude script/setup.js --exclude script/setup-test-e2e.js --exclude-dir node_modules -i *.* **/*.*`, { shell: true })
```

**Comment by navin-moorthy** [comment]
I do not get any error while running `pExecFile` with `{ shell: true }`.

But I get this error while running without `{ shell: true }`,

<details><summary>Error Details</summary>
<p>

```sh
> node script/setup-test-e2e.js

node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

Error: spawn grep --exclude script/setup.js --exclude script/setup-test-e2e.js --exclude-dir node_modules -i /JoshuaKGoldberg/ *.* **/*.* ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn grep --exclude script/setup.js --exclude script/setup-test-e2e.js --exclude-dir node_modules -i /JoshuaKGoldberg/ *.* **/*.*',
  path: 'grep --exclude script/setup.js --exclude script/setup-test-e2e.js --exclude-dir node_modules -i /JoshuaKGoldberg/ *.* **/*.*',
  spawnargs: [],
  cmd: 'grep --exclude script/setup.js --exclude script/setup-test-e2e.js --exclude-dir node_modules -i /JoshuaKGoldberg/ *.* **/*.*',
  stdout: '',
  stderr: ''
}
```
</p>
</details> 

While running below command,

```js
const { stdout } = await $`grep --exclude script/setup.js --exclude script/setup-test-e2e.js --exclude-dir node_modules -i /JoshuaKGoldberg/ *.* **/*.*`;
```

I get this error,

<details><summary>Error Details</summary>
<p>

```sh
> node script/setup-test-e2e.js

file:///Users/github/template-typescript-node-package/node_modules/.pnpm/execa@7.1.1/node_modules/execa/lib/error.js:59
		error = new Error(message);
		        ^

Error: Command failed with exit code 2: grep --exclude script/setup.js --exclude script/setup-test-e2e.js --exclude-dir node_modules -i /JoshuaKGoldberg/ *.* **/*.*
grep: *.*: No such file or directory
grep: **/*.*: No such file or directory
    at makeError (file:///Users/github/template-typescript-node-package/node_modules/.pnpm/execa@7.1.1/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///Users/github/template-typescript-node-package/node_modules/.pnpm/execa@7.1.1/node_modules/execa/index.js:124:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/github/template-typescript-node-package/script/setup-test-e2e.js:38:20 {
  shortMessage: 'Command failed with exit code 2: grep --exclude script/setup.js --exclude script/setup-test-e2e.js --exclude-dir node_modules -i /JoshuaKGoldberg/ *.* **/*.*',
  command: 'grep --exclude script/setup.js --exclude script/setup-test-e2e.js --exclude-dir node_modules -i /JoshuaKGoldberg/ *.* **/*.*',
  escapedCommand: 'grep --exclude "script/setup.js" --exclude "script/setup-test-e2e.js" --exclude-dir node_modules -i "/JoshuaKGoldberg/" "*.*" "**/*.*"',
  exitCode: 2,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'grep: *.*: No such file or directory\n' +
    'grep: **/*.*: No such file or directory',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v18.15.0
```

</p>
</details>

**Comment by ehmicky** [comment]
Thanks for the response @navin-moorthy,

It does not appear to be an error with Execa itself, but to confirm this, I would need to reproduce your setup. Would you it be possible for you to create a repository reproducing the above behavior? Thanks!

**Comment by navin-moorthy** [comment]
@ehmicky, here is the file https://github.com/JoshuaKGoldberg/template-typescript-node-package/blob/main/script/setup-test-e2e.js that is in discussion.

You can checkout & run `pnpm run setup:test` to execute this file.

Additional Reference: https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues/357

**Comment by ehmicky** [comment]
Hi @navin-moorthy,

I have tried to reproduce, but I am not encountering the same error as above. Would you be able to create a minimal GitHub repository which reproduces the above problem? Typically, it would only contain a single file to execute without any additional setup, with as few lines of code as possible to re-create the above error.

Thanks!

**Comment by navin-moorthy** [comment]
Here is the minimal reproduction in codesandbox - https://codesandbox.io/p/sandbox/quizzical-galois-bou50c?file=%2Findex.js

Github repo - https://github.com/navin-moorthy/execa-issue--555

**Comment by navin-moorthy** [comment]
Thanks @ehmicky for the explanation 👍

**Comment by navin-moorthy** [comment]
I found this quite useful using globby - https://github.com/google/zx/blob/main/docs/quotes.md#globbing-and-, https://github.com/google/zx/blob/main/README.md#globby-package

This solution works without `{shell: true}`.

```js
const files = await globby(["*.*", "**/*.*"]);

const output = await $`grep --exclude-dir=node_modules/* -i ${files}`;
```
