### ISSUE TITLE
Crash when running file without execute permissions

### ISSUE THREAD

**Issue by stigok** [sindresorhus/execa#58]
Steps to reproduce:

1. Create a normal file `touch foo.sh`
2. `chmod -x foo.sh` to be explicit.
3. `npm i execa`
3. Run `execa('foo.sh')` as below

```
// index.js
const execa = require('execa')
execa(__dirname + '/foo.sh')
  .then(() => console.log('Ran successfully'))
  .catch(err => console.error('Caught an error', err))
```

Crashes with error message
```
/repos/node_modules/execa/index.js:120
        spawned.then = promise.then.bind(promise);
                     ^

TypeError: Cannot set property 'then' of undefined
    at module.exports (/repos/node_modules/execa/index.js:120:15)
    at Object.<anonymous> (/repos/index.js:2:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
```

**Comment by sindresorhus** [comment]
I just released a new version with some major changes. Is it still reproducible? If yes, would you mind submitting a [failing test](https://github.com/avajs/ava#failing-tests)?

**Comment by stigok** [comment]
Not reproducable in v0.5.0. It now returns a rejected promise as expected.
