### ISSUE TITLE
[ASK] How to Defrag File using CMD

### ISSUE THREAD

**Issue by GusNando** [sindresorhus/execa#585]
hi guys, thank you for amazing package.

i want to ask a question, i want to run **defrag** using this package, and my code is

```js
import { $ } from 'execa';

const defrag = await $`defrag`;
```

if i tried to run this code using **node index.js** it will error like this

```
file:///C:/hasil/ping-cmd/node_modules/execa/lib/error.js:60
                error = new Error(message);
                        ^

Error: Command failed with exit code 1: defrag
'defrag' is not recognized as an internal or external command,
operable program or batch file.
    at makeError (file:///C:/hasil/ping-cmd/node_modules/execa/lib/error.js:60:11) 
    at handlePromise (file:///C:/hasil/ping-cmd/node_modules/execa/index.js:124:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
    at async file:///C:/hasil/ping-cmd/index2.js:3:16 {
  shortMessage: 'Command failed with exit code 1: defrag',
  command: 'defrag',
  escapedCommand: 'defrag',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: "'defrag' is not recognized as an internal or external command,\r\n" +
    'operable program or batch file.',
  cwd: 'C:\\hasil\\ping-cmd',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**its possible to run defrag in cmd using this package? thanks**

**Comment by ehmicky** [comment]
Hy @GusNando,

Does the following work?

```ts
const result = await $({ shell: true })`defrag`;
```

**Comment by ehmicky** [comment]
Closing because this question appears not to be related to Execa, but to process spawning in general.
